import { CalcInfo, ResinSpecification, UserProfile, ViscositySpindleFactor } from '../types';

export const CALCULATORS: CalcInfo[] = [
  {
    id: 'nco',
    name: 'Isocyanate Content (NCO%)',
    shortName: 'NCO %',
    symbol: '% NCO',
    unit: '%',
    category: 'Chemical',
    description: 'Titrimetric determination of free isocyanate groups in polyurethanes & prepolymers using standard HCl titrant.',
    formulaDisplay: 'NCO% = [(V_blank − V_sample) × N × 4.202] / W',
    iconName: 'FlaskConical',
    defaultMin: 2.0,
    defaultMax: 4.5,
    gaugeMin: 0,
    gaugeMax: 10,
  },
  {
    id: 'acid_value',
    name: 'Acid Value (AV)',
    shortName: 'Acid Value',
    symbol: 'AV',
    unit: 'mg KOH/g',
    category: 'Chemical',
    description: 'Measures free fatty acid or carboxylic acidity in polyester resins, alkyds, and polyols via KOH titration.',
    formulaDisplay: 'Acid Value = (V × N × 56.1) / W',
    iconName: 'TestTube2',
    defaultMin: 0.1,
    defaultMax: 2.5,
    gaugeMin: 0,
    gaugeMax: 10,
  },
  {
    id: 'karl_fischer',
    name: 'Moisture Content (KF %)',
    shortName: 'Karl Fischer',
    symbol: 'KF %',
    unit: '% H₂O',
    category: 'Analytical',
    description: 'Coulometric/volumetric moisture content determination in raw resins, solvents, and polymers.',
    formulaDisplay: 'Moisture % = (V × F × 100) / (W × 1000)',
    iconName: 'Droplets',
    defaultMin: 0.01,
    defaultMax: 0.15,
    gaugeMin: 0,
    gaugeMax: 1,
  },
  {
    id: 'hplc',
    name: 'HPLC Purity / Content',
    shortName: 'HPLC Content',
    symbol: 'HPLC %',
    unit: '%',
    category: 'Analytical',
    description: 'High-Performance Liquid Chromatography peak area quantification vs reference standard.',
    formulaDisplay: 'Content% = (Area_s / Area_std) × (W_std / W_s) × Purity_std × 100',
    iconName: 'BarChart2',
    defaultMin: 98.0,
    defaultMax: 100.0,
    gaugeMin: 80,
    gaugeMax: 100,
  },
  {
    id: 'viscosity',
    name: 'Brookfield Viscosity',
    shortName: 'Viscosity',
    symbol: 'Visc',
    unit: 'cP',
    category: 'Physical',
    description: 'Dynamic viscosity calculation using rotational dial reading and spindle speed factor table.',
    formulaDisplay: 'Viscosity (cP) = Dial Reading × Factor',
    iconName: 'Gauge',
    defaultMin: 1000,
    defaultMax: 3500,
    gaugeMin: 0,
    gaugeMax: 10000,
  },
  {
    id: 'hydroxyl',
    name: 'Hydroxyl Value (OH Value)',
    shortName: 'OH Value',
    symbol: 'OHV',
    unit: 'mg KOH/g',
    category: 'Chemical',
    description: 'Measures reactive hydroxyl groups in polyols and resins (corrected for acid value).',
    formulaDisplay: 'OH Value = [(V_blank − V_sample) × N × 56.1 / W] + Acid Value',
    iconName: 'Binary',
    defaultMin: 50,
    defaultMax: 180,
    gaugeMin: 0,
    gaugeMax: 300,
  },
  {
    id: 'nvm',
    name: 'Non-Volatile Matter (NVM%)',
    shortName: 'NVM % (Solids)',
    symbol: 'NVM%',
    unit: '%',
    category: 'Physical',
    description: 'Gravimetric determination of resin solid content following oven drying at 105°C-150°C.',
    formulaDisplay: 'NVM% = (W2 − W1) / (W3 − W1) × 100',
    iconName: 'Scale',
    defaultMin: 60.0,
    defaultMax: 80.0,
    gaugeMin: 0,
    gaugeMax: 100,
  },
  {
    id: 'specific_gravity',
    name: 'Specific Gravity (Pycnometer)',
    shortName: 'Sp. Gravity',
    symbol: 'Sp.Gr.',
    unit: 'g/cm³',
    category: 'Physical',
    description: 'Ratio of mass of a given volume of resin liquid to mass of equal volume of distilled water @25°C.',
    formulaDisplay: 'Specific Gravity = Weight of sample / Weight of water',
    iconName: 'Compass',
    defaultMin: 1.05,
    defaultMax: 1.18,
    gaugeMin: 0.8,
    gaugeMax: 1.5,
  },
  {
    id: 'gel_time',
    name: 'Gel Time / Pot Life',
    shortName: 'Gel Time',
    symbol: 'GelT',
    unit: 'min',
    category: 'Thermal/Kinetic',
    description: 'Reactivity timer for thermosetting resins from mixing start to gelation state transition.',
    formulaDisplay: 'Duration = Gel time − Start time',
    iconName: 'Timer',
    defaultMin: 15,
    defaultMax: 60,
    gaugeMin: 0,
    gaugeMax: 180,
  },
];

export const DEFAULT_USERS: UserProfile[] = [
  {
    id: 'usr_op_1',
    name: 'Alex Rivera',
    role: 'operator',
    employeeId: 'QC-4091',
    department: 'Polymer QC Lab - Shift A',
  },
  {
    id: 'usr_sup_1',
    name: 'Dr. Marcus Vance',
    role: 'supervisor',
    employeeId: 'SUP-1020',
    department: 'Quality Assurance Management',
  },
  {
    id: 'usr_admin_1',
    name: 'Elena Rostova',
    role: 'admin',
    employeeId: 'ADM-0001',
    department: 'Laboratory Systems Administrator',
  },
];

export const DEFAULT_RESIN_GRADES: ResinSpecification[] = [
  {
    id: 'grade_epoxy_e12',
    gradeName: 'Epoxy Resin E-12',
    category: 'Epoxy',
    specs: {
      nco: { min: 0, max: 0.2, unit: '%' },
      acid_value: { min: 0, max: 0.5, unit: 'mg KOH/g' },
      karl_fischer: { min: 0, max: 0.05, unit: '%' },
      viscosity: { min: 2000, max: 3200, unit: 'cP' },
      nvm: { min: 99.0, max: 100.0, unit: '%' },
      specific_gravity: { min: 1.15, max: 1.18, unit: 'g/cm³' },
      hydroxyl: { min: 160, max: 210, unit: 'mg KOH/g' },
    },
  },
  {
    id: 'grade_polyol_p2000',
    gradeName: 'Polyether Polyol P-2000',
    category: 'Polyurethane',
    specs: {
      hydroxyl: { min: 54, max: 58, unit: 'mg KOH/g' },
      acid_value: { min: 0, max: 0.05, unit: 'mg KOH/g' },
      karl_fischer: { min: 0, max: 0.03, unit: '%' },
      viscosity: { min: 300, max: 450, unit: 'cP' },
      nvm: { min: 99.5, max: 100.0, unit: '%' },
      specific_gravity: { min: 1.00, max: 1.02, unit: 'g/cm³' },
    },
  },
  {
    id: 'grade_pu_prepolymer_m50',
    gradeName: 'Isocyanate Prepolymer M-50',
    category: 'Polyurethane',
    specs: {
      nco: { min: 6.2, max: 6.8, unit: '%' },
      viscosity: { min: 1400, max: 1900, unit: 'cP' },
      karl_fischer: { min: 0, max: 0.02, unit: '%' },
      specific_gravity: { min: 1.08, max: 1.12, unit: 'g/cm³' },
      gel_time: { min: 20, max: 45, unit: 'min' },
    },
  },
  {
    id: 'grade_alkyd_60',
    gradeName: 'Medium Oil Alkyd 60%',
    category: 'Alkyd',
    specs: {
      acid_value: { min: 5.0, max: 10.0, unit: 'mg KOH/g' },
      nvm: { min: 59.0, max: 61.0, unit: '%' },
      viscosity: { min: 1800, max: 2500, unit: 'cP' },
      specific_gravity: { min: 0.94, max: 0.97, unit: 'g/cm³' },
    },
  },
];

export const DEFAULT_BROOKFIELD_FACTORS: ViscositySpindleFactor[] = [
  // LV Series
  { spindle: 'LV-1 (61)', rpm: 6, factor: 10 },
  { spindle: 'LV-1 (61)', rpm: 12, factor: 5 },
  { spindle: 'LV-1 (61)', rpm: 30, factor: 2 },
  { spindle: 'LV-1 (61)', rpm: 60, factor: 1 },
  { spindle: 'LV-2 (62)', rpm: 6, factor: 50 },
  { spindle: 'LV-2 (62)', rpm: 12, factor: 25 },
  { spindle: 'LV-2 (62)', rpm: 30, factor: 10 },
  { spindle: 'LV-2 (62)', rpm: 60, factor: 5 },
  { spindle: 'LV-3 (63)', rpm: 6, factor: 200 },
  { spindle: 'LV-3 (63)', rpm: 12, factor: 100 },
  { spindle: 'LV-3 (63)', rpm: 30, factor: 40 },
  { spindle: 'LV-3 (63)', rpm: 60, factor: 20 },
  { spindle: 'LV-4 (64)', rpm: 6, factor: 1000 },
  { spindle: 'LV-4 (64)', rpm: 12, factor: 500 },
  { spindle: 'LV-4 (64)', rpm: 30, factor: 200 },
  { spindle: 'LV-4 (64)', rpm: 60, factor: 100 },
  // RV Series
  { spindle: 'RV-2', rpm: 10, factor: 40 },
  { spindle: 'RV-2', rpm: 20, factor: 20 },
  { spindle: 'RV-2', rpm: 50, factor: 8 },
  { spindle: 'RV-2', rpm: 100, factor: 4 },
  { spindle: 'RV-3', rpm: 10, factor: 100 },
  { spindle: 'RV-3', rpm: 20, factor: 50 },
  { spindle: 'RV-3', rpm: 50, factor: 20 },
  { spindle: 'RV-3', rpm: 100, factor: 10 },
  { spindle: 'RV-4', rpm: 10, factor: 200 },
  { spindle: 'RV-4', rpm: 20, factor: 100 },
  { spindle: 'RV-4', rpm: 50, factor: 40 },
  { spindle: 'RV-4', rpm: 100, factor: 20 },
];
